/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project;

/**
 *
 * @author Rushil
 */

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;



public class addData extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form addData
     */
    public addData(int i) {
        initComponents();
        conn=db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
                size.height/2 - getHeight()/2);
        
        if(i==1)
        {
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel12.setVisible(false);
            txt_search.setVisible(false);
        }
        else if(i==2)
        {
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
        }
        else if(i==3)
        {
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jButton5.setVisible(true);
        }
         else if(i==4)
        {
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            jButton4.setVisible(true);
            jButton5.setVisible(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_sciname = new javax.swing.JTextField();
        txt_familyname = new javax.swing.JTextField();
        txt_habit = new javax.swing.JTextField();
        txt_habitat = new javax.swing.JTextField();
        txt_leaves = new javax.swing.JTextField();
        txt_bark = new javax.swing.JTextField();
        txt_flower = new javax.swing.JTextField();
        txt_fruit = new javax.swing.JTextField();
        txt_values_us = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id);
        txt_id.setBounds(90, 50, 180, 30);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name);
        txt_name.setBounds(90, 90, 180, 30);
        jPanel1.add(txt_sciname);
        txt_sciname.setBounds(90, 170, 180, 30);
        jPanel1.add(txt_familyname);
        txt_familyname.setBounds(90, 130, 180, 30);
        jPanel1.add(txt_habit);
        txt_habit.setBounds(90, 210, 180, 30);
        jPanel1.add(txt_habitat);
        txt_habitat.setBounds(90, 250, 180, 30);
        jPanel1.add(txt_leaves);
        txt_leaves.setBounds(90, 370, 180, 30);
        jPanel1.add(txt_bark);
        txt_bark.setBounds(90, 410, 180, 30);
        jPanel1.add(txt_flower);
        txt_flower.setBounds(90, 330, 180, 30);
        jPanel1.add(txt_fruit);
        txt_fruit.setBounds(90, 290, 180, 30);
        jPanel1.add(txt_values_us);
        txt_values_us.setBounds(90, 450, 180, 30);

        jLabel1.setText("Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 54, 40, 20);

        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(7, 94, 60, 30);

        jLabel3.setText("Scientific Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(2, 170, 90, 30);

        jLabel4.setText("Family Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 130, 80, 30);

        jLabel5.setText("Habit");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 210, 50, 30);

        jLabel6.setText("Habitat");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 254, 60, 20);

        jLabel7.setText("Bark");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 420, 60, 20);

        jLabel8.setText("Leaves");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 370, 60, 30);

        jLabel9.setText("Flower");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 330, 60, 30);

        jLabel10.setText("Values And Uses");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-1, 450, 90, 30);

        jLabel11.setText("Fruit");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 294, 50, 20);

        jButton1.setText("Add Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 440, 89, 50);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 440, 80, 50);

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(287, 52, 450, 370);

        jButton3.setText("Attach");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(480, 440, 80, 50);

        jLabel12.setText("Search plant");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 10, 90, 30);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(150, 10, 420, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 440, 80, 50);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(660, 440, 80, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database_project/Images/1952538752-images.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 750, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Add the Record?","Update Record",JOptionPane.YES_NO_OPTION); 
        if(x==0)
        {

            try 
            { 
                String sql ="insert into Image_information " 
                    + "(name,scientific_name,family_name,habit," 
                    + "habitat,leaves,bark," 
                    + "Image,flower,fruit,values_us) values (?,?,?,?,?,?,?,?,?,?,?) "; 

                pst=conn.prepareStatement(sql); 
                pst.setString(1,txt_name.getText()); 
                pst.setString(2,txt_sciname.getText()); 
                pst.setString(3,txt_familyname.getText());
                pst.setString(4,txt_habit.getText()); 
                pst.setString(5,txt_habitat.getText()); 
                pst.setString(6,txt_leaves.getText()); 
                pst.setString(7,txt_bark.getText()); 
                pst.setBytes(8, plant_image);
                pst.setString(9,txt_flower.getText()); 
               // pst.setString(10, gender); 
                pst.setString(10,txt_fruit.getText()); 
                pst.setString(11,txt_values_us.getText()); 
               /* pst.setString(13,txt_design.getText()); 
                pst.setString(14,txt_status.getText()); 
                pst.setString(15,txt_job.getText());
                pst.setString(16,txt_apt.getText()); 
                pst.setString(17,txt_doj.getText());*/ 

                pst.execute(); 

                JOptionPane.showMessageDialog(null,"Data is saved successfully"); 

            } 
            catch (Exception e) 
            { 
                 
                JOptionPane.showMessageDialog(null,e); 
            } 
            finally 
            { 
                try
                { 
                    rs.close(); 
                    pst.close();
                }
                catch(Exception e)
                { 
                    //JOptionPane.showMessageDialog(null,e); 
                }
            }
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txt_id.setText("");
        txt_name.setText("");
        txt_sciname.setText("");
        txt_familyname.setText("");
        txt_habit.setText("");
        txt_habitat.setText("");
        txt_leaves.setText(""); 
        txt_bark.setText("");
        txt_flower.setText("");
        txt_fruit.setText("");
        txt_values_us.setText("");
        
       // txt_design.setText(""); 
        img.setIcon(null);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        
        try
        {
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream ();
            byte [] buf = new byte[1024];
            
            for(int number ; (number=fix.read(buf))!= -1;)
            {
                bos.write(buf,0,number);
            }
            plant_image = bos.toByteArray();
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        try{ String sql ="select * from Image_information where id=? ";
                           
        
        pst=conn.prepareStatement(sql);
        pst.setString(1,txt_search.getText());
        rs=pst.executeQuery(); 
        
            String add1 =rs.getString("id"); 
            txt_id.setText(add1);
            
            String add2 =rs.getString("name");
            txt_name.setText(add2); 
            
            String add3 =rs.getString("scientific_name");
            txt_sciname.setText(add3); 
            
            String add4 =rs.getString("family_name");
            txt_familyname.setText(add4);
            
            String add5 =rs.getString("habit");
            txt_habit.setText(add5); 
            
            String add6 =rs.getString("habitat"); 
            txt_habitat.setText(add6); 
            
            String add7 =rs.getString("leaves");
            txt_leaves.setText(add7); 
            
            String add8 =rs.getString("bark");
            txt_bark.setText(add8);
            
            String add10 =rs.getString("flower"); 
            txt_flower.setText(add10); 
            
            String add11 =rs.getString("fruit");
            txt_fruit.setText(add11); 
            
            String add12 =rs.getString("values_us"); 
            txt_values_us.setText(add12);
            
            /*String add13 =rs.getString("Post_code");
            txt_pc.setText(add13); 
            
            String add14 =rs.getString("Status"); 
            txt_status.setText(add14); 
            
            String add15 =rs.getString("Date_hired"); 
            txt_doj.setText(add15); 
            
            String add16 =rs.getString("job_title"); 
            txt_job.setText(add16);
            
            String add17 =rs.getString("Designation");
            txt_design.setText(add17);*/ 
            
            byte[] image = rs.getBytes("Image");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH)); img.setIcon(imageIcon); }catch(Exception e){ } finally { try{ rs.close(); pst.close(); } catch(Exception e){ } }
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete?","Delete Record",JOptionPane.YES_NO_OPTION); 
        if(x==0)
        {
            try
            { 
                String sql ="delete from Image_information where id=? "; 
                pst=conn.prepareStatement(sql); 
                pst.setString(1, txt_id.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted"); 
            }
            catch(Exception e)
            { 
                JOptionPane.showMessageDialog(null, e); 
            }
            finally 
            { 
                try
                { 
                    rs.close(); pst.close();
                } 
                catch(Exception e)
                { } 
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        String value4 = txt_id.getText();
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION); 
        if(x==0)
        {
            try
            {
                 try
                 { 
                     String value1 = txt_name.getText();
                     String value2 = txt_sciname.getText();
                     String value3 = txt_familyname.getText();
                    // String value4 = txt_id.getText();
                     String value5 = txt_habit.getText(); 
                     String value6 = txt_habitat.getText();
                     String value7 = txt_leaves.getText(); 
                     String value8 = txt_bark.getText(); 
                     String value9 = txt_flower.getText(); 
                     String value10 = txt_fruit.getText(); 
                     String value11 = txt_values_us.getText();
                     /*String value12 = txt_design.getText(); 
                     String value13 = txt_status.getText();
                     String value14 = txt_salary.getText();
                     String value15 = txt_job.getText(); 
                     String value16 = txt_doj.getText();*/ 

                     String sql= "update Image_information set id='"+value4+"',name='"+value1+"', scientific_name='"+value2+"', "
                                + "family_name='"+value3+"',habit='"+value5+"',habitat='"+value6+"'," 
                                + "leaves='"+value7+"',bark='"+value8+"', flower = '"+value9+"', " 
                                + "fruit = '"+value10+"', values_us ='"+value11 
                                + "' where id='"+value4+"' ";

                     pst=conn.prepareStatement(sql);
                     pst.execute(); 

                     JOptionPane.showMessageDialog(null, "Record Updated"); 

                 }
                 catch(Exception e)
                 { 
                     JOptionPane.showMessageDialog(null, e); 

                 }
                 try
                 { 
                     File file = new File(filename);
                     FileInputStream fis = new FileInputStream(file); 
                     byte[] image = new byte[(int) file.length()]; 
                     fis.read(image); 
                     String sql = "update Image_information SET Image =? where id ='"+value4+"'"; 
                     pst = conn.prepareStatement(sql);
                     pst.setBytes(1, image);
                     pst.executeUpdate();
                     pst.close(); 
                 }
                 catch(Exception e)
                 { 
                     JOptionPane.showMessageDialog(null,e); 
                 }

                 finally 
                 { 
                     try
                     { 
                         rs.close(); 
                         pst.close(); 
                     } 
                     catch(Exception e)
                     { 
                     } 
                 }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Record Updated");
            }
            finally
            {
                try
                {

                }
                catch(Exception e)
                {

                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addData(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_bark;
    private javax.swing.JTextField txt_familyname;
    private javax.swing.JTextField txt_flower;
    private javax.swing.JTextField txt_fruit;
    private javax.swing.JTextField txt_habit;
    private javax.swing.JTextField txt_habitat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_leaves;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_sciname;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_values_us;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename = null;
    byte[] plant_image = null;

}
